# Generated by Django 3.0.5 on 2020-07-08 14:36

import blog.validator
import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('post', models.CharField(max_length=255)),
                ('image', models.ImageField(help_text='Size of Image must be 400*400', upload_to='our team')),
                ('choosedescription', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ApplicantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField()),
                ('photo', models.ImageField(upload_to='applicant_image', validators=[blog.validator.validate_file_size])),
                ('cv', models.FileField(upload_to='application_cv')),
                ('position', models.CharField(max_length=255)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacanacy Application List',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('heading1', models.CharField(max_length=255, unique=True)),
                ('heading2', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(help_text='Size of Image must be 1200*600', upload_to='banner')),
            ],
            options={
                'verbose_name_plural': 'Home Page Banner',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('slogan', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(help_text='Size of Image must be 219*55', upload_to='logo')),
                ('location', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('google', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Customer_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Customer_Record/Customer_Photo')),
                ('citizenship', models.FileField(blank=True, null=True, upload_to='Customer_Record/Customer_Citizenship')),
                ('passport', models.FileField(blank=True, null=True, upload_to='Customer_Record/Customer_Passport')),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Record',
            },
        ),
        migrations.CreateModel(
            name='Destination_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Destination Category',
            },
        ),
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribed User',
            },
        ),
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Message From')),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Home Page Pop Up',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(help_text='Size of Image must be 400*400', upload_to='Testimonial')),
                ('description', models.TextField()),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Customer Testimonial',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Low Level', 'Low Level'), ('Mid Level', 'Mid Level'), ('High Level', 'High Level')], max_length=255)),
                ('vacancynum', models.IntegerField()),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('lastdate', models.DateTimeField()),
                ('educationlevel', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('job_specification', ckeditor.fields.RichTextField()),
                ('job_description', ckeditor.fields.RichTextField()),
                ('apply_procedure', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('page_visit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Vacancy Post',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Newsletterimage')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.ManyToManyField(to='blog.NewsletterUser')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Creation',
            },
        ),
        migrations.CreateModel(
            name='Destination_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('depature', models.CharField(max_length=255)),
                ('person', models.IntegerField()),
                ('message', models.TextField()),
                ('destination_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Contacted', 'Contacted'), ('Done', 'Done')], default='Waiting', max_length=255)),
                ('booking', models.CharField(choices=[('confirm', 'confirm'), ('cancel', 'cancel'), ('waiting', 'waiting')], default='waiting', max_length=255)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Destination Customer Booking',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('star', models.IntegerField(default=0)),
                ('popular', models.BooleanField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('image', models.ImageField(help_text='Size of Image must be 500*333', upload_to='destination')),
                ('image1', models.ImageField(help_text='Size of Image must be 500*333', upload_to='destination')),
                ('image2', models.ImageField(help_text='Size of Image must be 500*333', upload_to='destination')),
                ('image3', models.ImageField(help_text='Size of Image must be 500*333', upload_to='destination')),
                ('image4', models.ImageField(help_text='Size of Image must be 500*333', upload_to='destination')),
                ('price', models.CharField(help_text='Please Mention Currency', max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('include', ckeditor.fields.RichTextField()),
                ('exclude', ckeditor.fields.RichTextField()),
                ('itenary', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Destination_Category')),
            ],
            options={
                'verbose_name_plural': 'Destination Package',
            },
        ),
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, help_text='Tick to show this on website')),
                ('created', models.DateField(null=True)),
                ('star', models.IntegerField(default=0)),
                ('latest', models.BooleanField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(help_text='Size of Image must be 400*400', upload_to='blimage')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('page_visit', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Admin_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Admin/Admin_Photo')),
                ('citizenship', models.FileField(blank=True, null=True, upload_to='Admin/Admin_Citizenship')),
                ('slc_certificate', models.FileField(blank=True, null=True, upload_to='Admin/Admin_SLC')),
                ('plus2_certificate', models.FileField(blank=True, null=True, upload_to='Admin/Admin_Plus2')),
                ('bachelor_certificate', models.FileField(blank=True, null=True, upload_to='Admin/Admin_Bachelor')),
                ('master_certificate', models.FileField(blank=True, null=True, upload_to='Admin/Admin_Master')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
