# Generated by Django 3.0.5 on 2020-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200709_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
